import psycopg2

def run_migration():
    conn = psycopg2.connect(
        dbname="ifms_budget",
        user="ifms_budget",
        password="ifms_budget",
        host="127.0.0.1",
        port="5432"
    )
    conn.autocommit = False
    cur = conn.cursor()

    try:
        # 1. Create table account_voucher
        print("1. Creating ifms_budget.account_voucher...")
        cur.execute("""
        CREATE TABLE IF NOT EXISTS ifms_budget.account_voucher (
            voucher_id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            sr_no               bigint,
            voucher_no          character varying(50) NOT NULL UNIQUE,
            voucher_type        character varying(30) DEFAULT 'REVENUE_RECEIPT' NOT NULL,
            voucher_date        date NOT NULL,
            financial_year      character varying(15) NOT NULL,
            pao_code            character varying(30) NOT NULL,
            
            -- Financial Values & Dual Chart of Accounts (Double Entry in Single Line)
            amount              numeric(17,2) NOT NULL,
            debit_coa_id        bigint NOT NULL REFERENCES ifms_budget.chart_of_account(coa_id),
            credit_coa_id       bigint NOT NULL REFERENCES ifms_budget.chart_of_account(coa_id),
            
            -- Expenditure & Departmental Linkages
            demand_id           bigint REFERENCES ifms_budget.demand(demand_id),
            department_id       bigint REFERENCES ifms_budget.department(department_id),
            ddo_id              bigint REFERENCES ifms_budget.ddo(ddo_id),
            office_id           bigint,
            scheme_id           bigint REFERENCES ifms_budget.scheme(scheme_id),
            project_id          bigint REFERENCES ifms_budget.project(project_id),
            
            -- Reconciliation & Bill Details
            recon_id            bigint REFERENCES ifms_budget.rev_recon_result(recon_id),
            bill_no             character varying(50),
            bill_date           date,
            payee_name          character varying(250),
            
            -- Workflow & Audit Details
            narration           text NOT NULL,
            status              character varying(30) DEFAULT 'Draft' NOT NULL,
            prepared_by         bigint REFERENCES ifms_budget.app_user(user_id),
            prepared_at         timestamp with time zone DEFAULT clock_timestamp(),
            checker_user_id     bigint REFERENCES ifms_budget.app_user(user_id),
            checker_remarks     text,
            approved_at         timestamp with time zone,
            
            -- Standard Enterprise Audit Columns
            organization_id     bigint DEFAULT 1 NOT NULL REFERENCES ifms_budget.organization(organization_id),
            org_branch_id       bigint DEFAULT 1 NOT NULL REFERENCES ifms_budget.branch(branch_id),
            created_by          bigint REFERENCES ifms_budget.app_user(user_id),
            updated_by          bigint REFERENCES ifms_budget.app_user(user_id),
            workflow_status     character varying(30) DEFAULT 'ACTIVE',
            created_at          timestamp with time zone DEFAULT clock_timestamp() NOT NULL,
            CONSTRAINT uq_account_voucher_no_sr UNIQUE (voucher_no, sr_no)
        );

        -- Ensure legacy single column constraint is dropped
        ALTER TABLE ifms_budget.account_voucher DROP CONSTRAINT IF EXISTS account_voucher_voucher_no_key;
        """)

        # 2. Migrate existing data if rev_receipt_voucher exists
        cur.execute("""
        SELECT EXISTS (
            SELECT 1 FROM information_schema.tables 
            WHERE table_schema = 'ifms_budget' AND table_name = 'rev_receipt_voucher'
        );
        """)
        old_table_exists = cur.fetchone()[0]

        if old_table_exists:
            print("2. Migrating data from rev_receipt_voucher and rev_voucher_item...")
            cur.execute("""
            INSERT INTO ifms_budget.account_voucher (
                voucher_id, sr_no, voucher_no, voucher_type, voucher_date, financial_year, pao_code,
                amount, debit_coa_id, credit_coa_id, demand_id, department_id, ddo_id, office_id,
                scheme_id, project_id, recon_id, bill_no, bill_date, payee_name, narration,
                status, prepared_by, prepared_at, checker_user_id, checker_remarks, approved_at,
                organization_id, org_branch_id, created_by, updated_by, workflow_status, created_at
            )
            SELECT
                v.voucher_id,
                COALESCE(v.sr_no, v.voucher_id) AS sr_no,
                v.voucher_no,
                v.voucher_type,
                v.voucher_date,
                v.financial_year,
                v.pao_code,
                v.credit_amount AS amount,
                COALESCE((SELECT coa_id FROM ifms_budget.rev_voucher_item WHERE voucher_id = v.voucher_id AND entry_type = 'DEBIT' LIMIT 1), 44) AS debit_coa_id,
                COALESCE((SELECT coa_id FROM ifms_budget.rev_voucher_item WHERE voucher_id = v.voucher_id AND entry_type = 'CREDIT' LIMIT 1), (SELECT coa_id FROM ifms_budget.chart_of_account WHERE coa_code = v.coa_id LIMIT 1), 36) AS credit_coa_id,
                NULL::bigint AS demand_id,
                v.department_id,
                NULL::bigint AS ddo_id,
                v.office_id,
                v.scheme_id,
                v.project_id,
                v.recon_id,
                NULL AS bill_no,
                NULL::date AS bill_date,
                NULL AS payee_name,
                v.narration,
                v.status,
                v.prepared_by,
                v.prepared_at,
                v.checker_user_id,
                v.checker_remarks,
                v.approved_at,
                v.organization_id,
                v.org_branch_id,
                v.created_by,
                v.updated_by,
                v.workflow_status,
                v.created_at
            FROM ifms_budget.rev_receipt_voucher v
            ON CONFLICT (voucher_id) DO UPDATE SET
                sr_no = EXCLUDED.sr_no,
                amount = EXCLUDED.amount,
                debit_coa_id = EXCLUDED.debit_coa_id,
                credit_coa_id = EXCLUDED.credit_coa_id;
            """)

            cur.execute("""
                SELECT setval(pg_get_serial_sequence('ifms_budget.account_voucher', 'voucher_id'), COALESCE((SELECT MAX(voucher_id) FROM ifms_budget.account_voucher), 1));
            """)

            # Drop old tables and dependencies
            print("3. Dropping legacy views, procedures, and tables...")
            cur.execute("DROP VIEW IF EXISTS ifms_budget.rev_vw_dashboard_kpis CASCADE;")
            cur.execute("DROP TABLE IF EXISTS ifms_budget.rev_voucher_item CASCADE;")
            cur.execute("DROP TABLE IF EXISTS ifms_budget.rev_receipt_voucher CASCADE;")

        # 4. Recreate View rev_vw_dashboard_kpis
        print("4. Recreating view rev_vw_dashboard_kpis...")
        cur.execute("""
        CREATE OR REPLACE VIEW ifms_budget.rev_vw_dashboard_kpis AS
        SELECT
            (SELECT COALESCE(SUM(amount), 0.00) FROM ifms_budget.rev_portal_transaction_staging WHERE is_valid = TRUE) AS total_portal_receipts,
            (SELECT COALESCE(SUM(amount), 0.00) FROM ifms_budget.rev_agency_bank_scroll_staging WHERE is_valid = TRUE) AS total_bank_scrolls,
            (SELECT COALESCE(SUM(amount), 0.00) FROM ifms_budget.rev_rbi_luggage_staging WHERE is_valid = TRUE) AS total_rbi_credit,
            (SELECT COUNT(*) FROM ifms_budget.rev_recon_result WHERE status = 'Matched') AS total_matched_records,
            (SELECT COALESCE(SUM(portal_total), 0.00) FROM ifms_budget.rev_recon_result WHERE status = 'Matched') AS total_matched_amount,
            (SELECT COUNT(*) FROM ifms_budget.rev_exception WHERE status IN ('Open', 'Assigned', 'Escalated')) AS pending_exceptions_count,
            (SELECT COUNT(*) FROM ifms_budget.rev_penal_claim WHERE status IN ('COMPUTED', 'DEMAND_ISSUED')) AS active_penal_claims_count,
            (SELECT COALESCE(SUM(penal_interest_outstanding), 0.00) FROM ifms_budget.rev_penal_claim WHERE status IN ('COMPUTED', 'DEMAND_ISSUED')) AS penal_interest_outstanding,
            (SELECT COUNT(*) FROM ifms_budget.account_voucher WHERE status = 'Draft') AS pending_vouchers_count,
            (SELECT COALESCE(SUM(amount), 0.00) FROM ifms_budget.account_voucher WHERE status = 'Draft') AS pending_vouchers_amount,
            (SELECT COUNT(*) FROM ifms_budget.rev_refund_case WHERE status NOT IN ('Paid', 'Rejected')) AS pending_refunds_count,
            (SELECT COUNT(*) FROM ifms_budget.rev_devolution_claim WHERE status <> 'Settled') AS pending_devolution_count;
        """)

        # 5. Drop old procedures and recreate
        print("5. Recreating stored procedures...")
        cur.execute("DROP PROCEDURE IF EXISTS ifms_budget.sp_rev_create_booking_vouchers(bigint, character varying);")
        cur.execute("DROP PROCEDURE IF EXISTS ifms_budget.sp_rev_create_booking_vouchers(bigint, text);")
        cur.execute("DROP PROCEDURE IF EXISTS ifms_budget.sp_rev_approve_booking_vouchers(bigint, text);")

        cur.execute("""
        CREATE OR REPLACE PROCEDURE ifms_budget.sp_rev_create_booking_vouchers(
            IN p_user_id bigint, 
            IN p_pao_code character varying DEFAULT 'PAO21'
        )
        LANGUAGE plpgsql
        AS $procedure$
        DECLARE
            v_item RECORD;
            v_vch_id bigint;
            v_vch_no character varying(50);
            v_clearing_coa_id bigint;
            v_penal_coa_id bigint;
            v_rev_coa_id bigint;
            v_amount numeric(17,2);
            v_next_sr bigint;
            v_org_id bigint := 1;
            v_branch_id bigint := 1;
        BEGIN
            SELECT organization_id, branch_id INTO v_org_id, v_branch_id FROM ifms_budget.branch LIMIT 1;
            IF v_org_id IS NULL THEN v_org_id := 1; v_branch_id := 1; END IF;

            -- Default Dr Suspense/Clearing Head (8658 Remittance in Transit)
            SELECT suspense_head_id, penal_interest_head_id INTO v_clearing_coa_id, v_penal_coa_id 
            FROM ifms_budget.rev_system_config WHERE config_id = 1;

            IF v_clearing_coa_id IS NULL THEN
                SELECT coa_id INTO v_clearing_coa_id FROM ifms_budget.chart_of_account WHERE coa_code LIKE '8658%' LIMIT 1;
            END IF;
            IF v_penal_coa_id IS NULL THEN
                SELECT coa_id INTO v_penal_coa_id FROM ifms_budget.chart_of_account WHERE coa_code = '8658-00-102-01-00-02' LIMIT 1;
                IF v_penal_coa_id IS NULL THEN v_penal_coa_id := v_clearing_coa_id; END IF;
            END IF;

            FOR v_item IN 
                SELECT res.recon_id, res.challan_no, res.payer_name, res.pao_code, res.receipt_head,
                       COALESCE(NULLIF(res.portal_total, 0), NULLIF(res.bank_total, 0), NULLIF(res.rbi_total, 0), 100.00)::numeric(17,2) as vch_amount,
                       COALESCE(res.penal_interest_amount, 0.00)::numeric(17,2) as penal_amount,
                       s.department_id, s.default_receipt_head_id
                FROM ifms_budget.rev_recon_result res
                LEFT JOIN ifms_budget.rev_revenue_source s ON s.source_code = res.revenue_source
                WHERE res.status = 'Matched' 
                  AND (p_pao_code IS NULL OR res.pao_code = p_pao_code)
                  AND res.booking_status IN ('UNBOOKED', 'READY_FOR_BOOKING')
            LOOP
                v_amount := v_item.vch_amount;
                IF v_amount <= 0 THEN v_amount := 100.00; END IF;

                -- Credit Revenue Head from source or receipt_head
                IF v_item.default_receipt_head_id IS NOT NULL THEN
                    v_rev_coa_id := v_item.default_receipt_head_id;
                ELSE
                    SELECT coa_id INTO v_rev_coa_id FROM ifms_budget.chart_of_account WHERE coa_code = v_item.receipt_head LIMIT 1;
                    IF v_rev_coa_id IS NULL THEN
                        SELECT coa_id INTO v_rev_coa_id FROM ifms_budget.chart_of_account LIMIT 1;
                    END IF;
                END IF;

                v_vch_no := ifms_budget.fn_rev_next_seq('VOUCHER_SEQ', 'VR', '2026-27');
                IF v_vch_no IS NULL OR v_vch_no = '' THEN
                    v_vch_no := 'VR-' || to_char(CURRENT_DATE, 'YYYYMMDD') || '-' || lpad(v_item.recon_id::text, 4, '0');
                END IF;

                -- Row 1: Principal Gross Amount (sr_no = 1)
                INSERT INTO ifms_budget.account_voucher (
                    sr_no, voucher_no, recon_id, voucher_date, voucher_type, financial_year, pao_code,
                    amount, debit_coa_id, credit_coa_id, department_id,
                    narration, status, prepared_by, prepared_at,
                    organization_id, org_branch_id, created_by, updated_by, workflow_status
                ) VALUES (
                    1, v_vch_no, v_item.recon_id, CURRENT_DATE, 'REVENUE_RECEIPT', '2026-27', v_item.pao_code,
                    v_amount, v_clearing_coa_id, v_rev_coa_id, v_item.department_id,
                    'Receipt booked upon 3-way reconciliation match for Challan ' || COALESCE(v_item.challan_no, '') || ' (' || COALESCE(v_item.payer_name, 'Payer') || ')',
                    'Draft', p_user_id, clock_timestamp(),
                    v_org_id, v_branch_id, p_user_id, p_user_id, 'ACTIVE'
                ) RETURNING voucher_id INTO v_vch_id;

                -- Row 2: Penal Interest Amount (sr_no = 2) if penal interest accrued
                IF v_item.penal_amount > 0 THEN
                    INSERT INTO ifms_budget.account_voucher (
                        sr_no, voucher_no, recon_id, voucher_date, voucher_type, financial_year, pao_code,
                        amount, debit_coa_id, credit_coa_id, department_id,
                        narration, status, prepared_by, prepared_at,
                        organization_id, org_branch_id, created_by, updated_by, workflow_status
                    ) VALUES (
                        2, v_vch_no, v_item.recon_id, CURRENT_DATE, 'REVENUE_RECEIPT', '2026-27', v_item.pao_code,
                        v_item.penal_amount, v_penal_coa_id, v_rev_coa_id, v_item.department_id,
                        'Penal interest remittance for SLA delay on Challan ' || COALESCE(v_item.challan_no, ''),
                        'Draft', p_user_id, clock_timestamp(),
                        v_org_id, v_branch_id, p_user_id, p_user_id, 'ACTIVE'
                    );
                END IF;

                UPDATE ifms_budget.rev_recon_result SET booking_status = 'DRAFT_VOUCHER' WHERE recon_id = v_item.recon_id;
            END LOOP;
        END;
        $procedure$;
        """)

        cur.execute("""
        CREATE OR REPLACE PROCEDURE ifms_budget.sp_rev_approve_booking_vouchers(
            IN p_checker_id bigint, 
            IN p_remarks text DEFAULT 'Verified and approved by PAO Checker.'
        )
        LANGUAGE plpgsql
        AS $procedure$
        BEGIN
            UPDATE ifms_budget.account_voucher
            SET status = 'Approved',
                checker_user_id = p_checker_id,
                checker_remarks = COALESCE(p_remarks, 'Verified and bulk approved by PAO Checker.'),
                approved_at = clock_timestamp(),
                updated_by = p_checker_id
            WHERE status = 'Draft';

            UPDATE ifms_budget.rev_recon_result
            SET booking_status = 'BOOKED',
                updated_at = clock_timestamp(),
                updated_by = p_checker_id
            WHERE recon_id IN (
                SELECT recon_id FROM ifms_budget.account_voucher WHERE status = 'Approved' AND recon_id IS NOT NULL
            ) AND booking_status != 'BOOKED';
        END;
        $procedure$;
        """)

        conn.commit()
        print("ALL DATABASE MIGRATIONS EXECUTED AND COMMITTED SUCCESSFULLY!")

    except Exception as e:
        conn.rollback()
        print("MIGRATION FAILED WITH ERROR:", e)
        raise e
    finally:
        cur.close()
        conn.close()

if __name__ == "__main__":
    run_migration()
