import React, { useEffect } from 'react';
import { useApp } from '../context/AppContext';

export const NotificationModal: React.FC = () => {
  const {
    isNotificationOpen,
    setIsNotificationOpen,
    notifications,
    markAllNotificationsRead,
  } = useApp();

  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === 'Escape' && isNotificationOpen) {
        setIsNotificationOpen(false);
      }
    };
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [isNotificationOpen, setIsNotificationOpen]);

  if (!isNotificationOpen) return null;

  return (
    <div
      className="ovl"
      role="dialog"
      aria-modal="true"
      onClick={() => setIsNotificationOpen(false)}
    >
      <div
        className="modal w520"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Modal Header */}
        <div className="modal-h">
          <div>
            <h3>Notifications</h3>
            <div className="sub">
              System alerts generated by uploads, reconciliation runs and workflow actions
            </div>
          </div>
          <button
            className="modal-x"
            aria-label="Close"
            onClick={() => setIsNotificationOpen(false)}
          >
            &times;
          </button>
        </div>

        {/* Modal Body */}
        <div className="modal-b">
          {notifications && notifications.length > 0 ? (
            <div className="timeline">
              {notifications.map((n) => {
                const cls =
                  n.level === 'ok'
                    ? 'ok'
                    : n.level === 'warn'
                    ? 'warn'
                    : n.level === 'err'
                    ? 'err'
                    : '';
                return (
                  <div key={n.id} className={`tl-item ${cls}`}>
                    <div className="tt">{n.title}</div>
                    <div className="small">{n.text}</div>
                    <div className="td">{n.ts}</div>
                  </div>
                );
              })}
            </div>
          ) : (
            <div className="empty">
              <span className="ic">🔔</span>
              No notifications.
            </div>
          )}
        </div>

        {/* Modal Footer */}
        <div className="modal-f">
          <button
            className="btn btn-p"
            onClick={() => markAllNotificationsRead()}
          >
            Mark all read
          </button>
          <button
            className="btn"
            onClick={() => setIsNotificationOpen(false)}
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
};
